spring:
  application:
    name: SpringStudy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springstudy
    username: jongg
    password: jongg
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: false
    encoding: utf-8
    mode: HTML
    template-resolver-order: 0
    excluded-view-names: /swagger-ui/index.html
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
    org.thymeleaf: info
    com.demo.spring: debug
    org.apache.tomcat: off
    org.springframework.boot: info
    org.postgresql: info
    org.hibernate: info
    org.hibernate.orm.jdbc.bind: trace
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    console: "%clr(%d){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

login:
  maxTryNo: 5

jwt:
  lifetime:
    minute: 10
  token:
    prefix: Bearer
    header: Authorization

decoder:
  type: RSA
