spring:
  application:
    name: jwt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springstudy
    username: jongg
    password: jongg
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: false
    encoding: utf-8
    mode: HTML
    template-resolver-order: 0
    excluded-view-names: /swagger-ui/index.html

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: debug
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    console: "%clr(%d){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"